name: My first cicd action  script

on:
  push: 
    branches: main



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    
    - name: Initialize Repo
      run: |
        echo "This is my first stage"
        uname -a

    - name: Check the Docker Installation
      run: |
        docker
        docker images

    - name: Run docker container
      run: |
        docker run hello-world
       
        
    
      
    
